### ISSUE TITLE
Dashboard Homepage corrections

### ISSUE THREAD

**Issue by mrtanshi** [princewhyte2/SMARTCOOPHQ#1]
Change grey background to white and change the grey (of the sections below) to #fcfdfd;
**To save seamlessly, you can transfer into your wallet account number from any bank at any time.
**My Wallet Account No.**
**How much do you want to save?**

The **TAP TO COPY** should only copy the account number not all the account information. Change the text to Tap to copy. Only T should be capital. Inglsih😁

@princewhyte2

**Comment by princewhyte2** [comment]
fixed close it out

**Comment by mrtanshi** [comment]
Sorry.  Pls Change grey background to white and change the grey (of the sections below) to  
f2f4f2

**Comment by mrtanshi** [comment]
Change the text to Tap to copy. Only T should be capital. Inglsih😁 @princewhyte2

**Comment by mrtanshi** [comment]
When account number is copied on mobile view, there are plenty White Spaces. 
**Sorry.** Pls Change grey background to white and change the grey (of the sections below) to
f2f4f2
**To save seamlessly, you can transfer into your wallet account number from any bank at any time.**
My Wallet Account No.
How much do you want to save?
@princewhyte2

**Comment by princewhyte2** [comment]
fixed close out

**Comment by mrtanshi** [comment]
Link to Inves
![image](https://user-images.githubusercontent.com/81524812/112770024-76b52880-901c-11eb-87a9-56f1e1fec72c.png)
