### ISSUE TITLE
Menu Button Choice

### ISSUE THREAD

**Issue by mrtanshi** [princewhyte2/SMARTCOOPHQ#8]
Use fries instead of Hamburger.
![image](https://user-images.githubusercontent.com/81524812/112765079-5cbb1c00-9003-11eb-8d8e-75ccc04861b6.png)

@princewhyte2

**Comment by princewhyte2** [comment]
fixed

**Comment by mrtanshi** [comment]
> fixed

Use the Kind of blue we use in the buttons...

**Comment by princewhyte2** [comment]
fixed close out
